### ISSUE TITLE
exception in threading

### ISSUE THREAD

**Issue by francosax** [richClubb/python-uds#46]
hi all,
I'm using the lib with vn1610 vector hardware , during a scan of service 22 xx yy I got this exception:
self.__recvBuffer.append(msg.data[self.__pduStartIndex:])
AttributeError: 'CanTp' object has no attribute '_CanTp__recvBuffer'
in file ....python_uds-1.0.2-py3.7.egg\uds\uds_communications\TransportProtocols\Can\CanTp.py

My script continue to run, but slowly: it sends 1 msg per second and not every 10 msec

**Comment by richClubb** [comment]
Hi Franco.

Can you send me your script? I've got access to a 1630 which should be similar enough to test this problem.

Rich

**Comment by francosax** [comment]
yes, at the moment I cannot acces to the pc, please take a look on the exceptions chain that I've already saved:
Exception in thread can.notifier for bus "Application testApp: CAN 1":
Traceback (most recent call last):
  File "D:\users\xxxxx\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "D:\users\xxxxx\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "D:\users\xxxxx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\python_can-3.2.0-py3.7.egg\can\notifier.py", line 102, in _rx_thread
    self._on_message_received(msg)
  File "D:\users\xxxxx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\python_can-3.2.0-py3.7.egg\can\notifier.py", line 119, in _on_message_received
    res = callback(msg)
  File "D:\users\xxxxx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\python_can-3.2.0-py3.7.egg\can\listener.py", line 54, in __call__
    return self.on_message_received(msg)
  File "D:\users\xxxxx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\python_uds-1.0.2-py3.7.egg\uds\uds_communications\TransportProtocols\Can\CanTp.py", line 371, in callback_onReceive
    self.__recvBuffer.append(msg.data[self.__pduStartIndex:])
AttributeError: 'CanTp' object has no attribute '_CanTp__recvBuffer'

**Comment by richClubb** [comment]
Hi Franco.

I'm not having any problems communicating with a CANcaseXL or 1630. Have you tried a very simple comms test?
```
from uds import Uds
a = Uds(reqId=0x600, resId=0x650, interface="vector", appName="pythonUds")
b = a.send([0x22, 0xf1, 0x8c])
print(b)
[98, 241, 140, 48, 48, 48, 48, 52, 57, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32]
```
You'll need to replace the "reqId" "resId" and "appName" as appropriate to your config. But otherwise I'm going to need the script you're using to debug further.

I also tried the following script on one of our test ECUs scanning all 65535 possible DIDs and it worked with the same setup.

```
from uds import Uds

if __name__ == "__main__":
    a = Uds(reqId=0x600, resId=0x650, interface="vector", appName="pythonUds")

    for i in range(0, 0xFF):
        for j in range(0, 0xFF):
            try:
                b = a.send([0x22, i, j])
            except:
                print("Nothing found on 0x{:02x}{:02x}".format(i,j))
            if(b[0] == 0x7F):
                print("Nothing found on 0x{:02x}{:02x}".format(i,j))
            else:
                print("Found {0} on 0x{:02x}{:02x}")
```

**Comment by francosax** [comment]
Hi Rich, attached here the code. Thanks!

**Comment by francosax** [comment]
Hi Rich, my configuration is OK, the problem is that after some time (maybe near 10 minutes) the exception appear and my script goes forward but very slowly (1 mesg per second) You can find attached here the code. Thanks!

**Comment by francosax** [comment]
Hi Rich, my configuration is OK, the problem is that after some time (maybe near 10 minutes) the exception appear and my script goes forward but very slowly (1 mesg per second) 
I do the same you did: scan of all did. You can find attached here the code. Thanks!

from time import sleep  # pragma: no cover
import sys  # pragma: no cover
import uds  # pragma: no cover
import can  # pragma: no cover
import logging  # pragma: no cover

UDS_SENDER = 0x7E0  # pragma: no cover
UDS_RESPONDER = 0x7E8  # pragma: no cover
EXCEPT_NO_ANS = True  # pragma: no cover
SERVICE_LIST = [0x22, 0x2E, 0x31, 0x10]  # pragma: no cover
SUBSERVICES_LIST = range(0, 0xFF + 1)  # [0xF1, 0x2E, 0x2F] #pragma: no cover
PARAMETERS_LIST = range(0, 0xFF + 1)  # pragma: no cover
TASK = 0.010  # pragma: no cover
# log to a file, events and varables
LOG_FILENAME = 'testUDS.log'  # pragma: no cover
# - %(levelname)s
LOG_FORMAT = '%(asctime)s - %(message)s'  # pragma: no cover
logging.basicConfig(filename=LOG_FILENAME, level=logging.ERROR, filemode='w', format=LOG_FORMAT)  # pragma: no cover


def send_tester_present():
    ans_to_tester_present = None
    try:
        my_uds = uds.Uds(reqId=UDS_SENDER, resId=UDS_RESPONDER, channel="0", interface="vector")
        # transmit a standard tester present
        ans_to_tester_present = my_uds.send([0x3E, 0x00], responseRequired=EXCEPT_NO_ANS)
        logging.warning('service_answer to ' + str(hex(0x3E)) + ' ' + str(hex(0x00)) + ' ' + ' : ' + \
		str(list(map(hex, ans_to_tester_present))))
        my_uds.disconnect()
        if ans_to_tester_present is None:
            logging.warning('No answer myreq_id: ', str(hex(UDS_SENDER)) + str(sys.exc_info()))
    except can.CanError:
        print("CanError: ")
        print("debug UDS_SENDER: ", hex(UDS_SENDER))
        print("debug, exceptionraised: ", sys.exc_info())
        logging.error('No answer UDS_SENDER: ', str(hex(UDS_SENDER)) + str(sys.exc_info()))
        pass
    print('answer to Tester Present: ', list(map(hex, ans_to_tester_present)))  # This should be [0x7E, 0x00]
    return ans_to_tester_present
	
	
	def test_uds_service():
    """ for XXX to be implemented
        - Write Data By Identifier Service (0x2E)
        - Routine Control Service (0x31)
        - Diagnostic Session Control Service (0x10)
        functionalReq=True, not supported yet
    """
    myreq_id = None
    service_answer = None
    try:
        for service_id in SERVICE_LIST:
            for myreq_id in SUBSERVICES_LIST:
                for mysubs_byte in PARAMETERS_LIST:
                    my_uds = uds.Uds(reqId=UDS_SENDER, resId=UDS_RESPONDER, channel="0", interface="vector")
                    # transmit a standard tester present
                    service_answer = my_uds.send([service_id, myreq_id, mysubs_byte], responseRequired=EXCEPT_NO_ANS)
                    if service_answer is not None:
                        logging.warning('service_answer to ' + str(hex(service_id)) + ' ' + str(hex(myreq_id)) + ' ' + \
						str(hex(mysubs_byte)) + ' ' + ' : ' + str((list(map(hex, service_answer)))))
                    else:
                        logging.warning(
                            'No answer to mesg: ' + str(hex(service_id)) + ' ' + str(hex(myreq_id)) + ' ' + \
							str(hex(mysubs_byte)))
                    sleep(TASK)
                    my_uds.disconnect()
    except can.CanError:
        print("CanError: ")
        print("debug myreq_id: ", hex(myreq_id))
        print("debug, exception raised: ", sys.exc_info())
        logging.error('No answer myreq_id: ' + str(hex(myreq_id)) + str(sys.exc_info()))
        pass
    print("\nEND test_uds_service")
    return service_answer
	
	
	def main():
    """
    --------------
    for XXX ECU
    --------------
    """  
    # send_tester_present()
    test_uds_service()


if __name__ == "__main__":
    main()

**Comment by francosax** [comment]
Hi Rich, my configuration is OK, the problem is that after some time (maybe near 10 minutes) the exception appear and my script goes forward but very slowly (1 mesg per second).
I'm running my script on python 3.7 32 bit on win10 and win7
I do the same you did: scan of all possible and also not allowed DID.  It is possible that the exception appears if I try not allowed DIDs?  You can find attached here the code. Thanks!


from time import sleep  # pragma: no cover
import sys  # pragma: no cover
import uds  # pragma: no cover
import can  # pragma: no cover
import logging  # pragma: no cover

UDS_SENDER = 0x7E0  # pragma: no cover
UDS_RESPONDER = 0x7E8  # pragma: no cover
EXCEPT_NO_ANS = True  # pragma: no cover
SERVICE_LIST = [0x22, 0x2E, 0x31, 0x10]  # pragma: no cover
SUBSERVICES_LIST = range(0, 0xFF + 1)  # [0xF1, 0x2E, 0x2F] #pragma: no cover
PARAMETERS_LIST = range(0, 0xFF + 1)  # pragma: no cover
TASK = 0.010  # pragma: no cover
# log to a file, events and varables
LOG_FILENAME = 'testUDS.log'  # pragma: no cover
# - %(levelname)s
LOG_FORMAT = '%(asctime)s - %(message)s'  # pragma: no cover
logging.basicConfig(filename=LOG_FILENAME, level=logging.ERROR, filemode='w', format=LOG_FORMAT)  # pragma: no cover


def send_tester_present():
    ans_to_tester_present = None
    try:
        my_uds = uds.Uds(reqId=UDS_SENDER, resId=UDS_RESPONDER, channel="0", interface="vector")
        # transmit a standard tester present
        ans_to_tester_present = my_uds.send([0x3E, 0x00], responseRequired=EXCEPT_NO_ANS)
        logging.warning('service_answer to ' + str(hex(0x3E)) + ' ' + str(hex(0x00)) + ' ' + ' : ' + \
		str(list(map(hex, ans_to_tester_present))))
        my_uds.disconnect()
        if ans_to_tester_present is None:
            logging.warning('No answer myreq_id: ', str(hex(UDS_SENDER)) + str(sys.exc_info()))
    except can.CanError:
        print("CanError: ")
        print("debug UDS_SENDER: ", hex(UDS_SENDER))
        print("debug, exceptionraised: ", sys.exc_info())
        logging.error('No answer UDS_SENDER: ', str(hex(UDS_SENDER)) + str(sys.exc_info()))
        pass
    print('answer to Tester Present: ', list(map(hex, ans_to_tester_present)))  # This should be [0x7E, 0x00]
    return ans_to_tester_present
	
	
	def test_uds_service():
    """ for XXX to be implemented
        - Write Data By Identifier Service (0x2E)
        - Routine Control Service (0x31)
        - Diagnostic Session Control Service (0x10)
        functionalReq=True, not supported yet
    """
    myreq_id = None
    service_answer = None
    try:
        for service_id in SERVICE_LIST:
            for myreq_id in SUBSERVICES_LIST:
                for mysubs_byte in PARAMETERS_LIST:
                    my_uds = uds.Uds(reqId=UDS_SENDER, resId=UDS_RESPONDER, channel="0", interface="vector")
                    # transmit a standard tester present
                    service_answer = my_uds.send([service_id, myreq_id, mysubs_byte], responseRequired=EXCEPT_NO_ANS)
                    if service_answer is not None:
                        logging.warning('service_answer to ' + str(hex(service_id)) + ' ' + str(hex(myreq_id)) + ' ' + \
						str(hex(mysubs_byte)) + ' ' + ' : ' + str((list(map(hex, service_answer)))))
                    else:
                        logging.warning(
                            'No answer to mesg: ' + str(hex(service_id)) + ' ' + str(hex(myreq_id)) + ' ' + \
							str(hex(mysubs_byte)))
                    sleep(TASK)
                    my_uds.disconnect()
    except can.CanError:
        print("CanError: ")
        print("debug myreq_id: ", hex(myreq_id))
        print("debug, exception raised: ", sys.exc_info())
        logging.error('No answer myreq_id: ' + str(hex(myreq_id)) + str(sys.exc_info()))
        pass
    print("\nEND test_uds_service")
    return service_answer
	
	
	def main():
    """
    --------------
    for XXX ECU
    --------------
    """  
    # send_tester_present()
    test_uds_service()


if __name__ == "__main__":
    main()

**Comment by francosax** [comment]
Hi Rich, my configuration is OK, the problem is that after some time (maybe near 10 minutes) the exception appear and my script goes forward but very slowly (1 mesg per second).
I'm running my script on python 3.7 32 bit on win10 and win7
I do the same you did: scan of all possible and also not allowed DID. It is possible that the exception appears if I try not allowed DIDs? 
I tried to attach my source file but seems that with firefox browser it not work well...

**Comment by richClubb** [comment]
Hi Franco.

Please email it to richard.clubb@embeduk.com and I'll have a look.

**Comment by francosax** [comment]
Hi Rich, please close the issue. I fixed the issue. It was a memory issue due to my fault in use of Uds lib.

**Comment by richClubb** [comment]
Hi Franco.

Could you explain. I'd like to see if there is any way to improve the
quality of the code.

Sincerely

Rich

**Comment by francosax** [comment]
Hi Rich, I was wrong in a for loop in wich I don't destroy the uds object at the end, so when the script was runnig it accumulates more and more uds objects in memory...so.... Was my fault.

**Comment by richClubb** [comment]
Hi Franco.

Thanks for explaining this.

Let me know if there is anything else you need.

Sincerely,

Rich.
