### ISSUE TITLE
canTp recv "Timeout in waiting for message"

### ISSUE THREAD

**Issue by chrizgeo** [richClubb/python-uds#65]
recv sometimes raises "Timeout in waiting for message" when multiple frames are sent from the server .
There is no issues in receiving single frames. 
This timeout error occurs ### only around once in ten times.  I am trying to get the response for _report DTC by status mask_.

**Comment by prajwal-bs-urs** [comment]
I am facing a similar issue with $0x31 to verify checksum. But in my case this issue occurs every single time. Please find the error below:

Traceback (most recent call last):
  File "C:/Users/rxb/PycharmProjects/pythonProject/EOL_Automation/certification_injection.py", line 206, in <module>
    checksumVerify = TCM.send([0x31, 0x01, 0xFF, 0x01, 0x01, 0x85, 0x90])
  File "C:\Users\rxb\PycharmProjects\venv\lib\site-packages\uds\uds_communications\Uds\Uds.py", line 165, in send
    a = self.tp.send(msg, functionalReq)
  File "C:\Users\rxb1\PycharmProjects\venv\lib\site-packages\uds\uds_communications\TransportProtocols\Can\CanTp.py", line 230, in send
    raise Exception("Timeout waiting for message")
**Exception: Timeout waiting for message**

Please let me know how to resolve this issue.
